#pragma once

namespace perfetto
{
    class TracingSession;
}

#ifdef FREYR_PROFILING

    #include <perfetto.h>

PERFETTO_DEFINE_CATEGORIES(
    perfetto::Category("FREYR").SetDescription(
        "Events generated by the Frey internal execution"),
    perfetto::Category("USER").SetDescription(
        "Events generated by the User requests"));

    #define FREYR_PROFILING_BEGIN(category, name, ...)                         \
        TRACE_EVENT_BEGIN(category, name, __VA_ARGS__)
    #define FREYR_PROFILING_END(category, ...)                                 \
        TRACE_EVENT_END(category, __VA_ARGS__)

#else

    #define FREYR_PROFILING_BEGIN(category, name, ...)
    #define FREYR_PROFILING_END(category, ...)

#endif // FREYR_PROFILING