#pragma once

namespace perfetto
{
    class TracingSession;
}

#ifdef FREYR_PROFILING

    #include <perfetto.h>

PERFETTO_DEFINE_CATEGORIES(
    perfetto::Category("FREYR").SetDescription("Events generated by the Freyr internal execution"),
    perfetto::Category("USER").SetDescription("Events generated by the User code execution"));

    #define FREYR_TRACE(category, name)            TRACE_EVENT(category,  perfetto::DynamicString{name})
    #define FREYR_TRACE_BEGIN(category, name, ...) TRACE_EVENT_BEGIN(category, perfetto::DynamicString{name}, __VA_ARGS__)
    #define FREYR_TRACE_END(category, ...)         TRACE_EVENT_END(category, __VA_ARGS__)
#else

    #define FREYR_TRACE(category, name)
    #define FREYR_TRACE_BEGIN(category, name, ...)
    #define FREYR_TRACE_END(category, ...)

#endif // FREYR_PROFILING
