#include "Freyr/Core/Profiling.hpp"

#ifdef FREYR_PROFILING
    #include <chrono>
    #include <cstring>
    #include <format>
    #include <fstream>
    #include <perfetto.h>

PERFETTO_DEFINE_CATEGORIES(
    perfetto::Category("FREYR").SetDescription("Events generated by the Freyr internal execution"),
    perfetto::Category("USER").SetDescription("Events generated by the User code execution"));

PERFETTO_TRACK_EVENT_STATIC_STORAGE();

namespace FREYR_NAMESPACE
{
    namespace
    {
        thread_local std::uint64_t gTraceTrackId = 0;

        bool IsUserCategory(const char* category)
        {
            return std::strcmp(category, "USER") == 0;
        }

        perfetto::Track MakeLaneTrack(std::uint64_t trackId)
        {
            return perfetto::Track(trackId, perfetto::ProcessTrack::Current());
        }

        void TraceBegin(const char* category, const char* name, std::uint64_t trackId)
        {
            const auto track = MakeLaneTrack(trackId);
            if (IsUserCategory(category))
                TRACE_EVENT_BEGIN("USER", perfetto::DynamicString { name }, track);
            else
                TRACE_EVENT_BEGIN("FREYR", perfetto::DynamicString { name }, track);
        }

        void TraceEnd(const char* category, std::uint64_t trackId)
        {
            const auto track = MakeLaneTrack(trackId);
            if (IsUserCategory(category))
                TRACE_EVENT_END("USER", track);
            else
                TRACE_EVENT_END("FREYR", track);
        }
    } // namespace

    std::uint64_t FreyrCurrentTraceTrackId()
    {
        return gTraceTrackId;
    }

    void FreyrSetTraceTrackId(std::uint64_t trackId)
    {
        gTraceTrackId = trackId;
    }

    FreyrScopedTrace::FreyrScopedTrace(const char* category, const char* name, std::uint64_t trackId)
        : mCategory(category), mTrackId(trackId)
    {
        TraceBegin(category, name, trackId);
    }

    FreyrScopedTrace::~FreyrScopedTrace()
    {
        TraceEnd(mCategory, mTrackId);
    }

    void FreyrTraceBegin(const char* category, const char* name, std::uint64_t trackId)
    {
        TraceBegin(category, name, trackId);
    }

    void FreyrTraceEnd(const char* category, std::uint64_t trackId)
    {
        TraceEnd(category, trackId);
    }

    void FreyrRegisterMainThreadTrack()
    {
        FreyrSetTraceTrackId(0);
    }

    void FreyrRegisterWorkerTracks(std::size_t workerCount)
    {
        for (std::size_t i = 1; i <= workerCount; ++i)
        {
            const auto label = std::format("Thread: {:0>2}", i);
            TraceBegin("FREYR", label.c_str(), i);
            TraceEnd("FREYR", i);
        }
    }

    std::unique_ptr<perfetto::TracingSession> FreyrStartTracingSession()
    {
        auto args = perfetto::TracingInitArgs();
        args.backends |= perfetto::kInProcessBackend;

        perfetto::Tracing::Initialize(args);
        perfetto::TrackEvent::Register();

        perfetto::protos::gen::TrackEventConfig track_event_cfg;

        perfetto::TraceConfig cfg;
        cfg.add_buffers()->set_size_kb(1024 * 1024);

        auto* ds_cfg = cfg.add_data_sources()->mutable_config();
        ds_cfg->set_name("track_event");
        ds_cfg->set_track_event_config_raw(track_event_cfg.SerializeAsString());

        auto session = perfetto::Tracing::NewTrace();
        session->Setup(cfg);
        session->StartBlocking();
        return session;
    }

    void FreyrStopTracingSession(perfetto::TracingSession& session)
    {
        session.StopBlocking();
        const auto trace_data = session.ReadTraceBlocking();

        auto trace_name = std::format("freyr_trace_{}.pftrace",
                                      std::chrono::system_clock::now().time_since_epoch().count());

        std::ofstream output(trace_name.c_str(), std::ios::out | std::ios::binary);
        output.write(trace_data.data(), static_cast<std::streamsize>(trace_data.size()));
    }
} // namespace FREYR_NAMESPACE
#endif // FREYR_PROFILING
