#include "Freyr/Core/Profiling.hpp"

#ifdef FREYR_PROFILING
    #include <chrono>
    #include <cstring>
    #include <format>
    #include <fstream>
    #include <perfetto.h>

PERFETTO_DEFINE_CATEGORIES(
    perfetto::Category("FREYR").SetDescription("Events generated by the Freyr internal execution"),
    perfetto::Category("USER").SetDescription("Events generated by the User code execution"));

PERFETTO_TRACK_EVENT_STATIC_STORAGE();

namespace FREYR_NAMESPACE
{
    namespace
    {
        bool IsUserCategory(const char* category)
        {
            return std::strcmp(category, "USER") == 0;
        }
    } // namespace

    FreyrScopedTrace::FreyrScopedTrace(const char* category, const char* name) : mCategory(category)
    {
        if (IsUserCategory(category))
            TRACE_EVENT_BEGIN("USER", perfetto::DynamicString { name });
        else
            TRACE_EVENT_BEGIN("FREYR", perfetto::DynamicString { name });
    }

    FreyrScopedTrace::~FreyrScopedTrace()
    {
        if (IsUserCategory(mCategory))
            TRACE_EVENT_END("USER");
        else
            TRACE_EVENT_END("FREYR");
    }

    void FreyrTraceBegin(const char* category, const char* name)
    {
        if (IsUserCategory(category))
            TRACE_EVENT_BEGIN("USER", perfetto::DynamicString { name });
        else
            TRACE_EVENT_BEGIN("FREYR", perfetto::DynamicString { name });
    }

    void FreyrTraceEnd(const char* category)
    {
        if (IsUserCategory(category))
            TRACE_EVENT_END("USER");
        else
            TRACE_EVENT_END("FREYR");
    }

    std::unique_ptr<perfetto::TracingSession> FreyrStartTracingSession()
    {
        auto args = perfetto::TracingInitArgs();
        args.backends |= perfetto::kInProcessBackend;

        perfetto::Tracing::Initialize(args);
        perfetto::TrackEvent::Register();

        perfetto::protos::gen::TrackEventConfig track_event_cfg;

        perfetto::TraceConfig cfg;
        cfg.add_buffers()->set_size_kb(1024 * 1024);

        auto* ds_cfg = cfg.add_data_sources()->mutable_config();
        ds_cfg->set_name("track_event");
        ds_cfg->set_track_event_config_raw(track_event_cfg.SerializeAsString());

        auto session = perfetto::Tracing::NewTrace();
        session->Setup(cfg);
        session->StartBlocking();
        return session;
    }

    void FreyrStopTracingSession(perfetto::TracingSession& session)
    {
        session.StopBlocking();
        const auto trace_data = session.ReadTraceBlocking();

        auto trace_name = std::format(
            "freyr_trace_{}.pftrace",
            std::chrono::system_clock::now().time_since_epoch().count());

        std::ofstream output(trace_name.c_str(), std::ios::out | std::ios::binary);
        output.write(trace_data.data(), static_cast<std::streamsize>(trace_data.size()));
    }
} // namespace FREYR_NAMESPACE
#endif // FREYR_PROFILING
